### ISSUE TITLE
Use official redux-offline.

### ISSUE THREAD

**Issue by silverskyvicto** [mattermost/mattermost-redux#1058]
Hi.

The official `redux-offline` package has been renamed to 
[@redux-offline/redux-offline](https://www.npmjs.com/package/@redux-offline/redux-offline) and seems to be under development.

https://github.com/mattermost/mattermost-redux/blob/d5f581cfed3ffc273d0e7ca02663dd8fd6b8c241/package.json#L35

How about use this?

**Comment by enahum** [comment]
Hi @silverskyvicto we do have our own fork with custom changes and we haven’t updated it as it has a few breaking changes.

Is there any reason or functionality that you need in a more recent version? Perhaps you want to take a further look in detail and update it as well as apply the changes introduced by us, then make sure the webapp and the mobile app work as expected or add the needed changes as well.

Let us know.

**Comment by hmhealey** [comment]
This can be closed now since we no longer user redux-offline. Thanks for the feedback though!
