### ISSUE TITLE
Without chrome extension Redux Dev Tools the webapp throws errors

### ISSUE THREAD

**Issue by watadarkstar** [mattermost/mattermost-redux#354]
#### Summary
If you don't have the chrome extension [Redux Dev Tools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) installed you get a whole bunch of errors (see below) that cause the webapp to "explode" in development.

![image pasted at 2017-12-13 10-28](https://user-images.githubusercontent.com/3059371/33947672-024429d8-dff3-11e7-88bd-198faeb68171.png)

#### Environment Information

- Webapp: ?
- Mattermost Server Version: ?

#### Steps to reproduce
Install the webapp dev environment without [Redux Dev Tools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) installed.

#### Expected behavior
Would be nice to have this disabled by default and or more gracefully handle these errors.

#### Observed behavior
Error messages (see screenshot above).

#### Possible fixes
In [configureStore.dev.js](https://github.com/mattermost/mattermost-redux/blob/e2b61264d5226a561e69475fe553c59ec8aa1fa3/src/store/configureStore.dev.js) there is a bunch of stuff regarding [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools). More specifically look into disabling the tools if `window.__REDUX_DEVTOOLS_EXTENSION__` doesn't exist. See these lines of code:

https://github.com/mattermost/mattermost-redux/blob/e2b61264d5226a561e69475fe553c59ec8aa1fa3/src/store/configureStore.dev.js#L15-L23

**Comment by hanzei** [comment]
I can't reproduce this issue with Mattermost 5.5. Do this still occur @watadarkstar?

**Comment by watadarkstar** [comment]
This is a really old issue @hanzei

**Comment by hanzei** [comment]
Sure, I know. Mind if I close it?

**Comment by watadarkstar** [comment]
Yup can be closed.
