### ISSUE TITLE
Unable to join channel via slash command using channel name with tilde

### ISSUE THREAD

**Issue by kaleposhobios** [mattermost/mattermost-redux#566]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When I try to use the slash command like so: `/join ~off-topic` it fails.

#### Environment Information

- Webapp or React Native app: Webapp
- Mattermost Server Version: 5.0.0

#### Steps to reproduce
1. Try to join a channel with the following command: `/join ~off-topic`

#### Expected behavior
/join command works. Please note that it DOES work if you do `/join off-topic`.

#### Observed behavior
2. Notice you get system message "An error occurred while listing channels"
3. Notice logs: 
{"level":"error","ts":1531408785.8157103,"caller":"web/handlers.go:140","msg":"You do not have the appropriate permissions","path":"/api/v4/channels/4a611cw6w3gy7rna3zaukcq1xa/members/me","request_id":"rkr8zjsmqi85jrnrxkbrdhqh9r","ip_addr":"172.17.0.1","user_id":"drxfunkhzbf3dkuit35zrnmsrh","method":"GET","err_where":"Permissions","http_code":403,"err_details":"userId=drxfunkhzbf3dkuit35zrnmsrh, permission=read_channel"}

#### Possible fixes
It seems likely to me it has something to do with the logic here: https://github.com/mattermost/mattermost-redux/blob/master/src/actions/channels.js#L664 where if it gets the channel name it does one thing (which I think is the case that works) and if it gets the channel id (which it makes sense if you use tilde then it finds the channel id and tries to post that instead) it does another thing. Why it's trying to list members first before adding (which is what it seems to be doing) I don't know.

**Comment by hanzei** [comment]
Hi @kaleposhobios
I tested again with Mattermost v5.5 and it seams to work just fine.

I'm closing this issue for now. Please reopen, if this bug still occurs.
