### ISSUE TITLE
When uploading multiple images with same timestamp, the redux fails

### ISSUE THREAD

**Issue by zetaab** [mattermost/mattermost-redux#616]
After this PR https://github.com/mattermost/mattermost-redux/pull/582 is merged we have problem in 5.2 if multiple images in same post are uploaded at the same timestamp
<img width="1267" alt="screen shot 2018-08-28 at 16 21 48" src="https://user-images.githubusercontent.com/22482503/44727280-57f7f980-aae2-11e8-8a15-43663fdbb9fa.png">

For some reason the original postid is "locale". I tried to debug this problem but could not find why the locale is postid. Anyways all images has locale = postid instead of real locale. The problem exists only if two images has exact same timestamp. Then it is trying to do localeCompare in https://github.com/mattermost/mattermost-redux/blob/master/src/utils/file_utils.js#L97 but fails because the locale variable is postid.

**Comment by amyblais** [comment]
Hi @zetaab!

The Jira ticket for the PR you referenced has been re-opened as it needs some additional fixing, so I added a note in it about the bug you are seeing: https://mattermost.atlassian.net/browse/MM-10621.

I'll create a new ticket for this if our devs determine that it should be fixed separately.

**Comment by saturninoabril** [comment]
@zetaab That's weird.  I can't see how it's being passed as postId instead of locale in [sortFileInfos](https://github.com/mattermost/mattermost-redux/blob/master/src/utils/file_utils.js#L91).  You'll notice that the said locale is a props of CreatePost and CreateComment which is basically from the selector [getCurrentLocale](https://github.com/mattermost/mattermost-webapp/blob/master/components/create_post/index.js#L71).
Are you using the release version of 5.2?
If possible, could you give a repro steps/files for these?

Thanks for the report!

**Comment by zetaab** [comment]
I tried to reproduce it myself as well, but I could not. Anyways the key thing is to upload many files at the same time. At least two files should have same timestamp.

The json for files is 
```
[{"id":"83nry87b8trfudogkjt71344dw","user_id":"8fa9tyyk7jymzgbemhuy6ert9w","post_id":"ngkaqozwqtdtxgeykwsc84y11r","create_at":1535459022330,"update_at":1535459022330,"delete_at":0,"name":"Näyttökuva 2018-08-28 kello 15.19.20.png","extension":"png","size":205674,"mime_type":"image/png","width":1262,"height":1264,"has_preview_image":true},{"id":"iuk4ow81ppgmigzr8ugeahq7tr","user_id":"8fa9tyyk7jymzgbemhuy6ert9w","post_id":"ngkaqozwqtdtxgeykwsc84y11r","create_at":1535459022330,"update_at":1535459022330,"delete_at":0,"name":"Näyttökuva 2018-08-28 kello 15.18.52.png","extension":"png","size":161012,"mime_type":"image/png","width":1248,"height":1110,"has_preview_image":true},{"id":"bi97e1g1zbyh8qt513kss89hqw","user_id":"8fa9tyyk7jymzgbemhuy6ert9w","post_id":"ngkaqozwqtdtxgeykwsc84y11r","create_at":1535459022340,"update_at":1535459022340,"delete_at":0,"name":"Näyttökuva 2018-08-28 kello 15.21.12.png","extension":"png","size":272901,"mime_type":"image/png","width":1256,"height":1256,"has_preview_image":true},{"id":"1ajneqtocpy48cgpf36gux3g4w","user_id":"8fa9tyyk7jymzgbemhuy6ert9w","post_id":"ngkaqozwqtdtxgeykwsc84y11r","create_at":1535459022463,"update_at":1535459022463,"delete_at":0,"name":"Näyttökuva 2018-08-28 kello 15.21.55.png","extension":"png","size":212716,"mime_type":"image/png","width":1228,"height":1256,"has_preview_image":true}]
```
After this is requested from api, the user interface will crash.

**Comment by saturninoabril** [comment]
Thanks!  Are you using release version of 5.2 (not modified)?

**Comment by zetaab** [comment]
that part of the ui is default 5.2

**Comment by saturninoabril** [comment]
Sorry @zetaab but I really couldn't repro this issue and can't see how to fix this.  I guess we'll revisit this case whenever we have reproducible steps.

**Comment by hanzei** [comment]
@zetaab Can you still reproduce this issue?

**Comment by zetaab** [comment]
it might be that this was fixed in https://github.com/mattermost/mattermost-redux/pull/685 but I cannot reproduce it anymore because we set now default language for all users.

**Comment by hanzei** [comment]
Closing this one for now. Please open again @zetaab if you encounter this problem again.
