### ISSUE TITLE
[Help Wanted] [PLT-5984] Split out constants even more

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-redux#88]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-5984)

**Comment by enahum** [comment]
please be aware that this will affect [mattermost-mobile](https://github.com/mattermost/mattermost-mobile) and [platform](https://github.com/mattermost/platform)

**Comment by hanzei** [comment]
@enahum Maybe this issue should be reposted on https://github.com/mattermost/mattermost-server/issues?

**Comment by enahum** [comment]
@hanzei that would be a task for @esethna but I do agree, all help wanted tickets should be kept in the server repo

**Comment by hanzei** [comment]
@esethna ^

**Comment by hanzei** [comment]
@esethna ^

**Comment by hanzei** [comment]
Reopened in https://github.com/mattermost/mattermost-server/issues/10362
