### ISSUE TITLE
Running React Native app with mattermost-redux fails.

### ISSUE THREAD

**Issue by avegrv** [mattermost/mattermost-redux#978]
#### Summary
Running React Native app with mattermost-redux fails.

#### Steps to reproduce
- npm i  mattermost-redux --save
- react-native run-ios

####  Expected behavior
The React Native app should start without error.

#### Observed behavior

> error: bundling failed: Error: Unable to resolve module `core-js/modules/web.dom-collections.iterator` from `/Users/node_modules/mattermost-redux/store/configureStore.dev.js`: Module `core-js/modules/web.dom-collections.iterator` does not exist in the Haste module map

####  Possible fixes
Install additional deps
- @react-native-community/netinfo
- core-js
- remote-redux-devtools

**Comment by enahum** [comment]
@avegrv as you can see in https://github.com/mattermost/mattermost-mobile that is a react native app and the use of mattermost-redux just works, perhaps those deps should be included in your own project?

**Comment by avegrv** [comment]
Correct, those deps should be included in my own project, but unfortunately, it's hard to guess.
It seems to me the best solution would be to exclude these dependencies from the `configureStore` call.

**Comment by enahum** [comment]
Possibly. Perhaps they can be added as peerDependencies in this project. Would you mind submitting a PR?

**Comment by avegrv** [comment]
Yes, Elias, I will try tomorrow. Thank you.

**Comment by avegrv** [comment]
@enahum Fixed at #981. I found that the problem was with core-js. 
Also, I will create a separate issue to remove offline features of library. I think that code that depends on:
- redux-offline
- @react-native-community/netinfo

must be on the mobile version of mattermost. Because working with offline is the responsibility of the mobile application only. Let's disccuss it in separate issue – #982.
