### ISSUE TITLE
Updated dependency fails RN app

### ISSUE THREAD

**Issue by chuttam** [mattermost/mattermost-redux#983]
#### Summary
Recent version bump (d4b655287768cd72089a3f82e43652a9b4e1008b) to `serialize-errors` prevents RN app from running.

#### Steps to reproduce
mattermost-redux: With current HEAD on `master` (2289b684b65ac1f9fe438a1b7139523a20143102):  
* `make clean`
* `make`

mattermost-mobile: With current HEAD on `master` (https://github.com/mattermost/mattermost-mobile/commit/e5e3bcc84441ed20eb5060bf64f6312b396c9041):  
* `make clean`
* `make pre-run`
* `make run-ios/run-android`

With these steps, the mobile app should fail when building bundle with the following redbox:

<img width="364" alt="Screen Shot 2019-11-13 at 10 19 21" src="https://user-images.githubusercontent.com/887849/68767219-16783f00-05ff-11ea-9c4b-fc250cba3b1d.png">

#### Possible fixes

So, [this recent commit](https://github.com/mattermost/mattermost-redux/commit/d4b655287768cd72089a3f82e43652a9b4e1008b) prevents RN app `master` from building, if it is pointed to latest mattermost-redux commit.

We've had the [same issue before](https://github.com/mattermost/mattermost-redux/pull/822), but this time I can't just do a simple revert because there's a pre-commit hook fails the `implicit anys` rule for library dependencies. This prevents the `serialize-error` library from going back to an older version.

I'm looking at options, including possibly removing `serialize-error`, but this is a more involved effort. Another option could be to somehow not run the pre-commit hook on dependency libraries?

**Comment by enahum** [comment]
it looks like the better option is to add a peer dependency for `util` on this project and then add it in RN.

I'll be adding it to RN in a PR that updates mattermost-redux

**Comment by enahum** [comment]
PR here https://github.com/mattermost/mattermost-mobile/pull/3553

**Comment by reflog** [comment]
@chuttam - does @enahum solution work for you or should the package be downgraded anyway?

**Comment by chuttam** [comment]
@reflog @enahum's solution takes care of the issue. Feel free to reject my PR.

**Comment by reflog** [comment]
Great! Closing
